### ISSUE TITLE
Kinetic Merge faults with scala.MatchError.

### ISSUE THREAD

**Issue by sageserpent-open** [sageserpent-open/kineticMerge#126]
Seen on commit: af43499fb0074db44336ed03897f656e71237087.

Merging the Kinetic Merge repository, from commit af43499fb0074db44336ed03897f656e71237087 (using a build from that commit) to 7c26c131ededa8eb7fc28022e9683055506c4b58.

Exception:

```scala
scala.MatchError: Section(
  label = "OURS: issue-35-limit-ambiguous-matches",
  path = /Users/gerardmurphy/IdeaProjects/kineticMerge/src/main/scala/com/sageserpent/kineticmerge/core/CodeMotionAnalysis.scala,
  start = TextPosition(line = 1306, characterOffset = 16),
  onePastEnd = TextPosition(line = 1312, characterOffset = 25),
  startTokenIndex = 6492,
  sizeInTokens = 13,
  content summary = """)
              else
                matchingFingerprintsAcrossSides(
                  baseFingerprints ... rightFingerprints.tail,
                  matches"""
```

Full stacktrace:

```text
	at com.sageserpent.kineticmerge.core.MappedContentSources.pathFor(MappedContentSources.scala:164)
	at com.sageserpent.kineticmerge.core.MappedContentSources.pathFor$(MappedContentSources.scala:12)
	at com.sageserpent.kineticmerge.core.MappedContentSourcesOfTokens.pathFor(MappedContentSources.scala:229)
	at com.sageserpent.kineticmerge.core.CodeMotionAnalysis$$anon$3.rightPathFor(CodeMotionAnalysis.scala:1971)
	at com.sageserpent.kineticmerge.core.CodeMotionAnalysisExtension$.anchoredContentFromOppositeSide$2(CodeMotionAnalysisExtension.scala:366)
	at com.sageserpent.kineticmerge.core.CodeMotionAnalysisExtension$.mergesFrom$1(CodeMotionAnalysisExtension.scala:588)
	at com.sageserpent.kineticmerge.core.CodeMotionAnalysisExtension$.$anonfun$37(CodeMotionAnalysisExtension.scala:680)
	at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:727)
	at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:721)
	at scala.collection.AbstractIterable.foldLeft(Iterable.scala:935)
	at com.sageserpent.kineticmerge.core.CodeMotionAnalysisExtension$.merge(CodeMotionAnalysisExtension.scala:671)
	at com.sageserpent.kineticmerge.Main$InWorkingDirectory.indexUpdates$$anonfun$2$$anonfun$2(Main.scala:1251)
	at cats.data.EitherT.bimap$$anonfun$1(EitherT.scala:423)
	at cats.data.WriterT.map$$anonfun$1(WriterT.scala:138)
	at apply$extension @ com.sageserpent.kineticmerge.Main$.com$sageserpent$kineticmerge$Main$$$right(Main.scala:379)
	at apply @ com.sageserpent.kineticmerge.Main$.com$sageserpent$kineticmerge$Main$$$labelExceptionWith(Main.scala:385)
	at apply @ com.sageserpent.kineticmerge.Main$.com$sageserpent$kineticmerge$Main$$$labelExceptionWith(Main.scala:385)
	at flatMap @ com.sageserpent.kineticmerge.Main$.mergeTheirBranch(Main.scala:358)
	at apply$extension @ com.sageserpent.kineticmerge.Main$.com$sageserpent$kineticmerge$Main$$$right(Main.scala:379)
	at apply @ com.sageserpent.kineticmerge.Main$.com$sageserpent$kineticmerge$Main$$$labelExceptionWith(Main.scala:385)
	at foldM @ com.sageserpent.kineticmerge.Main$InWorkingDirectory.indexUpdates(Main.scala:1229)
	at foldM @ com.sageserpent.kineticmerge.Main$InWorkingDirectory.indexUpdates(Main.scala:1229)
	at apply$extension @ com.sageserpent.kineticmerge.Main$.com$sageserpent$kineticmerge$Main$$$right(Main.scala:379)
	at apply @ com.sageserpent.kineticmerge.Main$.com$sageserpent$kineticmerge$Main$$$labelExceptionWith(Main.scala:385)
	at apply @ com.sageserpent.kineticmerge.Main$.com$sageserpent$kineticmerge$Main$$$labelExceptionWith(Main.scala:385)
	at foldM @ com.sageserpent.kineticmerge.Main$InWorkingDirectory.indexUpdates(Main.scala:1229)
	at foldM @ com.sageserpent.kineticmerge.Main$InWorkingDirectory.indexUpdates(Main.scala:1229)
	at apply$extension @ com.sageserpent.kineticmerge.Main$.com$sageserpent$kineticmerge$Main$$$right(Main.scala:379)
	at apply @ com.sageserpent.kineticmerge.Main$.com$sageserpent$kineticmerge$Main$$$labelExceptionWith(Main.scala:385)
```

**Comment by sageserpent-open** [comment]
An initial debugging sessions shows that the opposite side anchor of a plain move whose destination is *our* side, namely on the left, is itself **also a left** side section with label of `OURS`.

This section came from the `MoveEvaluation`, so the problem is either in its construction, or possibly upstream in the first-pass merge that collects speculative migrations by source / speculative move destinations.

**Comment by sageserpent-open** [comment]
Once this is sorted out, it would be instructive to compare the merge outcome with that of c9b01d5036d4029395bc4b57d899e743339e35fe, which was done by manually (and tediously) resolving a conventional Git merge.

**Comment by sageserpent-open** [comment]
Commit f4972723e3dba52476f8697cf5259934ed7b0057 has a test to reproduce this bug.

Commit c4fb3ce1243d0f69f874d0b38a0671859f0aef66 fixes the test failure, and the example merge described above now results in a successful merge without conflicts.

The merge is *not* perfect, for example:

```scala
        val sectionsByPotentialMatchKey

        val FingerprintSectionsAcrossSides(
          baseSectionsByPotentialMatchKey,
          leftSectionsByPotentialMatchKey,
          rightSectionsByPotentialMatchKey
        baseSectionsByPotentialMatchKey =
            sectionsByPotentialMatchKey(baseSources, pathInclusions.isIncludedOnBase)
        val leftSectionsByPotentialMatchKey =
            sectionsByPotentialMatchKey(leftSources),
          rightSectionsByPotentialMatchKey =
            sectionsByPotentialMatchKey(rightSources)
        )

        @tailrec
        def matchKeysAcrossSides(
            basePotentialMatchKeys: Iterable[PotentialMatchKey],
            leftPotentialMatchKeys: Iterable[PotentialMatchKey],
            rightPotentialMatchKeys, pathInclusions.isIncludedOnLeft)
        val , pathInclusions.isIncludedOnRight: Iterable[PotentialMatchKey],
            matches: Set[GenericMatch],
            haveTrimmedMatches: Boolean
        ): MatchingResult =

```

and:

```scala
              val (withAdditionalMatches, haveTrimmedAdditionalMatches) =
                if superfluous.isEmpty then
                  (matches ++ permitted.map(Match.BaseAndLeft.apply)) -> false
                else
                  logger.warn(
                    s"Discarding ambiguous all-sides matches of content: ${pprintCustomised(permitted.head._1.content)} as there are more than $maximumNumberOfMatchesSharingContent matches."
                  )
                  matches -> true

              matchKeysAcrossSides(
                    basePotentialMatchKeys.tail,
                    leftPotentialMatchKeys.tail,
                    rightPotentialMatchKeysmatchKeysAcrossSides(
                    basePotentialMatchKeys.tail,
                    leftPotentialMatchKeys.tail,
                    rightPotentialMatchKeys,
                    withAdditionalMatches,
                haveTrimmedMatches || haveTrimmedAdditionalMatches
              )
```

Nevertheless, compare the results from a Git merge:

```scala
<<<<<<< HEAD
        def fingerprintSections(
            sources: Sources[Path, Element],
            pathIsIncluded: Path => Boolean
        ): SortedMultiDict[PotentialMatchKey, Section[Element]] =
          SortedMultiDict.from(
            sources.filesByPath
              .filter { case (path, file) =>
                pathIsIncluded(path) && {
                  val fileSize          = file.size
                  val minimumWindowSize = thresholdSizeForMatching(fileSize)

                  minimumWindowSize to fileSize contains windowSize
                }
              }
              .par
              .flatMap { case (path, file) =>
                fingerprintStartIndices(file.content).map(
                  (fingerprint, fingerprintStartIndex) =>
                    val section = sources
                      .section(path)(fingerprintStartIndex, windowSize)
                    PotentialMatchKey(
                      fingerprint,
                      impliedContent = section
                    ) -> section
                )
              }
          )
        end fingerprintSections

        val baseSectionsByFingerprint =
          fingerprintSections(baseSources, pathInclusions.isIncludedOnBase)
        val leftSectionsByFingerprint =
          fingerprintSections(leftSources, pathInclusions.isIncludedOnLeft)
        val rightSectionsByFingerprint =
          fingerprintSections(rightSources, pathInclusions.isIncludedOnRight)

        @tailrec
        def matchingFingerprintsAcrossSides(
            baseFingerprints: Iterable[PotentialMatchKey],
            leftFingerprints: Iterable[PotentialMatchKey],
            rightFingerprints: Iterable[PotentialMatchKey],
            matches: Set[GenericMatch],
            haveTrimmedMatches: Boolean
=======
        def sectionsByPotentialMatchKey(
            sources: Sources[Path, Element]
        ): SortedMultiDict[PotentialMatchKey, Section[Element]] =
          sources.filesByPath
            .filter { case (_, file) =>
              val fileSize          = file.size
              val minimumWindowSize = thresholdSizeForMatching(fileSize)

              minimumWindowSize to fileSize contains windowSize
            }
            .par
            .map { case (path, file) =>
              fingerprintStartIndices(file.content).map(
                (fingerprint, fingerprintStartIndex) =>
                  val section = sources
                    .section(path)(fingerprintStartIndex, windowSize)
                  PotentialMatchKey(
                    fingerprint,
                    impliedContent = section
                  ) -> section
              )
            }
            // This isn't quite the same as flat-mapping / flattening, because
            // we want the type of the result to be a `SortedMultiDict`...
            .reduceOption(_ concat _)
            .getOrElse(SortedMultiDict.empty)
        end sectionsByPotentialMatchKey

        val FingerprintSectionsAcrossSides(
          baseSectionsByPotentialMatchKey,
          leftSectionsByPotentialMatchKey,
          rightSectionsByPotentialMatchKey
        ) = FingerprintSectionsAcrossSides(
          baseSectionsByPotentialMatchKey =
            sectionsByPotentialMatchKey(baseSources),
          leftSectionsByPotentialMatchKey =
            sectionsByPotentialMatchKey(leftSources),
          rightSectionsByPotentialMatchKey =
            sectionsByPotentialMatchKey(rightSources)
        )

        @tailrec
        def matchKeysAcrossSides(
            basePotentialMatchKeys: Iterable[PotentialMatchKey],
            leftPotentialMatchKeys: Iterable[PotentialMatchKey],
            rightPotentialMatchKeys: Iterable[PotentialMatchKey],
            matches: Set[GenericMatch]
>>>>>>> af43499
```

Git merge essentially gave up and reported large conflicts.

The merge by Kinetic Merge could be finessed a lot more, but it's on the right track, and the fault is no longer observed.

**Comment by sageserpent-open** [comment]
Branch `main` fast-forwarded to c4fb3ce1243d0f69f874d0b38a0671859f0aef66.

**Comment by sageserpent-open** [comment]
As a last word, rebuilding Kinetic Merge 04d26a3c8ea1995051ee62dbd887ced4b4e435d6 (which includes this work) and running with the invocation:

```bash
/Users/gerardmurphy/IdeaProjects/kineticMerge/target/kinetic-merge --no-commit --minimum-ambiguous-match-size=2 af43499
```

Yields a much better, albeit still slightly flawed merge.

The second dubious snippet from Kinetic Merge shown above is now:

```scala
              val (withAdditionalMatches, haveTrimmedAdditionalMatches) =
                if superfluous.isEmpty then
                  (matches ++ permittedmatchKeysAcrossSides(
                    basePotentialMatchKeys.tail,
                    leftPotentialMatchKeys.tail,
                    rightPotentialMatchKeys.map(Match.BaseAndLeft.apply)) -> false
                else
                  logger.warn(
                    s"Discarding ambiguous all-sides matches of content: ${pprintCustomised(permitted.head._1.content)} as there are more than $maximumNumberOfMatchesSharingContent matches."
                  )
                  matches -> true

              matchKeysAcrossSides(
                    basePotentialMatchKeys.tail,
                    leftPotentialMatchKeys.tail,
                    rightPotentialMatchKeys,
                    withAdditionalMatches,
                haveTrimmedMatches || haveTrimmedAdditionalMatches
              )
```

That happens to be the right outcome for that snippet.

**Comment by sageserpent-open** [comment]
This went out in Release 1.4.0.
