### ISSUE TITLE
Assertion failure when running Kinetic Merge in `MoveDestinations.isDegenerate`.

### ISSUE THREAD

**Issue by sageserpent-open** [sageserpent-open/kineticMerge#48]
# Version: 1.2.5

# Reproduction

1. Set up a blank Git repository.
2. Switch to new branch: `git checkout -b master`.
3. Commit file `aFile.txt` with content of:
```text
This is the first line,
followed by the second.

Can you see where this is going?
Need a hint?
THE END.
```
4. Tag the commit with `git tag base`.
5. Switch to new branch: `git checkout -b renaming`
6. `git mv aFile.txt theRenamedFile.txt`.
7. Edit the content of `theRenamedFile.txt` to be:
```text
This is the first line,
followed by the second.

Can you see where this is going?
Need a hint? No, good - you're a quick study.
THE END.
```
8. Update the index: `git add theRenamedFile.txt`.
9. Commit the rename and edit.
10. Switch back to `master`: `git checkout master`.
11. Edit the content of `aFile.txt` to be:
```text
This is the obligatory zeroth line.
Can you see where this is going?
Need a hint?
This was the first line,
followed by the second.

THE END.
```
12. Update the index: `git add aFile.txt`.
13. Commit the edit.
14. Run Kinetic Merge to bring in the renaming + edit: `kinetic-merge --no-commit renaming`.
This will fault with a stacktrace of:
```text
Exception in thread "main" scala.MatchError: java.lang.IllegalArgumentException: requirement failed (of class java.lang.IllegalArgumentException)
	at com.sageserpent.kineticmerge.Main$.apply$$anonfun$1(Main.scala:240)
	at scala.util.Success.fold(Try.scala:281)
	at com.sageserpent.kineticmerge.Main$.apply(Main.scala:243)
	at com.sageserpent.kineticmerge.Main$.main(Main.scala:78)
	at com.sageserpent.kineticmerge.Main.main(Main.scala)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at coursier.bootstrap.launcher.a.a(Unknown Source)
	at coursier.bootstrap.launcher.ResourcesLauncher.main(Unknown Source)
```

# Discussion

Debugging shows that this is down to a requirement assertion failure in [`com.sageserpent.kineticmerge.core.MoveDestinations#isDegenerate`](https://github.com/sageserpent-open/kineticMerge/blob/1e55332f215b7c1882ca22cb824622acaebc4c23/src/main/scala/com/sageserpent/kineticmerge/core/MoveDestinations.scala#L47).

**Comment by sageserpent-open** [comment]
While we're at it, that diagnostic is lousy - what we should see is the original requirement assertion failure with the stacktrace of where it was thrown. What we currently see is some exception handling code that wasn't expecting to see the `IllegalArgumentException` propagated up.

Need to fix that as a prelude to the bug-fix.

**Comment by sageserpent-open** [comment]
1. As of cc7477cad70b87d2d095da6a15d0814341be3193, the bug leads to a better diagnostic when running Kinetic Merge.
2. A bug reproduction test has been added: `MainTest.issue48BugReproduction` - and it fails!
3. Looking at the logging from the failing test shows that the base form of `aFile.txt` has a filler section of `THE END.`, whereas the left form of `aFile.txt` and the right form of `theRenamedFile.txt` have left-right matching sections of `.\nTHE END.`. Now this isn't very pretty, but it is valid, and provokes the bug...
4. Investigation reveals two problems:
    1. The requirement assertion is part of the invariant for `MoveDestinations`. It asserts that if the move destination is *degenerate*, i.e. there is no source for the move, then it must be either a divergent move where matched sections are inserted at different locations (possibly in different files) or is a coincident move where the matched sections align in the same file. The problem here is that a divergent move is picked up in distinct left moves and right moves, possibly across distinct files, so the invariant is temporarily boken while the overall `MoveDestinationsReport` is being built up. It is straightforward enough to hoist the requirement assertion out of `MoveDestinations` and into `CodeMotionAnalysisExtension.merge` to become an assumption, valid once all the per-file merges have been collated together.
    2. Solving the first problem leads to the next - there is an edit-versus-deletion merge conflict when `aFile.txt` is merged, where the edit replaces the filler section `THE END.` with `.\nTHE END.` on the left. That does *not* lead to a left move being registered, whereas `theRenamedFile.txt` does register a right move. Thus both the original invariant and the more relaxed assumption break.

**Comment by sageserpent-open** [comment]
Interestingly, the change mentioned above in 4.i. is enough to get a conflicted merge if the minumum match size is set to 3 (the default is 4). This allows an all-sides match of `THE END.` and shifts the left-right match to the preceding `.\n`. That left-right match results in a straight divergent insertion move across the two files.

**Comment by sageserpent-open** [comment]
The crux of 4.ii is that we have what would be a divergent insertion, but one side of the insertion is hidden by virtue of being in a edit-versus-delete merge conflict.

What should this look like, bearing in mind that what was the base section was nearly a match for the inserted sections...?

**Comment by sageserpent-open** [comment]
Musing about the previous comment's questions - if a move destination (be it divergent or not, or a migration or an insertion) shows up in a conflict (be it edit-versus-delete or edit-versus-edit), then it really is a move, regardless of whether the user resolving the merge decides to keep it in preference to the other side of the conflict, or allow both in some order, or meld them together, or delete it in favour of the other side, or just completely rewrite the conflict to something new.

The fact is, the conflict records two competing valid bits of content, and one of the them is a move destination.

So we should record it as such.

The other thing is, given the changes made in #43, why didn't the base section act as a gap chunk and thus make a last-minute match in the merge? The answer is, because the left and right actually made a match, and these are held as sacrosanct; *matched* sections are not considered for breaking up by gap chunks. All of which makes me wonder whether it's worth finding a way of rooting out small matches that are not ambiguous. Here we go again...

**Comment by sageserpent-open** [comment]
Spike work done in 99951ff339415d9a4f02d91d24a30db616d5f7b4 shows that a fix is feasible, but exposes another unrelated bug; spun out a new issue for that: #49.

Now to write more tests and complete the cut over of the conflict handling logic in `MatchesContext`...

**Comment by sageserpent-open** [comment]
While reviewing `MatchesContextTest`, it occurs to me that the codebase tracks moves via their *destinations* - this is reflected in the tests for the merge algebra furnished by `MatchesContext` - only incoming moves appear in test expectations.

On the other hand, migrations have to picked up at the move *sources* - which is fine, only they are associated with the move destinations. This feels a bit odd - why not associate them with the move sources and apply the migrations by referring back to the move sources that match a given move destination. One to ponder...

**Comment by sageserpent-open** [comment]
As of 8d47ce7231cc32c7ae066e8e0e5434694bfa16c5, new tests added into `MatchesContextTest`, these detect failures in the code prior to the spike, and pass subsequent to it.

**Comment by sageserpent-open** [comment]
This went out in Release 1.3.0.
